services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sgodonto_backend_local
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: "http://localhost:8085"
    ports:
      - "3001:3000"
    networks:
      - local-network
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sgodonto_frontend_local
    environment:
      # Nginx config is static, but this forces rebuild if needed
      FORCE_REBUILD: "true"
    ports:
      - "8085:80"
    networks:
      - local-network
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15-alpine
    container_name: sgodonto_db_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - local-network
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_local:


networks:
  local-network:
    driver: bridge
