services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sgodonto_backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      FORCE_REBUILD: "true"
      # S3 / MinIO Config for Docker Internal Network
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT}
    ports:
      - "3001:${BACKEND_PORT}"
    networks:
      - dokploy-network
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/main"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sgodonto_frontend
    environment:
      FORCE_REBUILD: "true"
    ports:
      - "${FRONTEND_PORT:-8085}:80"
    networks:
      - dokploy-network
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15-alpine
    container_name: sgodonto_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - dokploy-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio
    container_name: sgodonto_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - dokploy-network
    restart: always

volumes:
  postgres_data:
  minio_data:


networks:
  dokploy-network:
    external: true
